apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "203"
    field.cattle.io/publicEndpoints: '[{"addresses":["10.109.172.57"],"port":80,"protocol":"HTTP","serviceName":"kuick-prod:dealcore2server","ingressName":"kuick-prod:nginx.kaikeba.com","hostname":"nginx.kaikeba.com","path":"/","allNodes":false}]'
    prometheus.io/scrape: "true"  # determines if a pod should be scraped. Set to true to enable scraping.
    prometheus.io/path: "/manage/metrics" # determines the path to scrape metrics at. Defaults to /metrics.
    prometheus.io/port: "8081"
  creationTimestamp: null
  generation: 1
  labels:
    app: deal-core2-server
    chart: deal-core2-server-2.0.0-1273fa
    env: pro
    heritage: Helm
    language: java
    namespace: kuick-prod
    release: dealcore2server
    serviceKind: backend
  name: dealcore2server
  namespace: kuick-prod
  selfLink: /apis/apps/v1/namespaces/kuick-prod/deployments/dealcore2server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deal-core2-server
      release: dealcore2server
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: deal-core2-server
        release: dealcore2server
    spec:
      containers:
        - env:
            - name: SAMPLING_ENABLE
              value: "true"
            - name: SAMPLING_RATE
              value: "10"
            - name: SENTRY_ENABLE
              value: "true"
            - name: SENTRY_ENVIRONMENT
              value: prod
            - name: SENTRY_SERVERNAME
              value: deal-core2-server
            - name: SPRING_CLOUD_CONFIG_ENABLED
              value: "true"
            - name: SPRING_CLOUD_CONFIG_PROFILE
              value: pro
            - name: SPRING_CLOUD_CONFIG_URI
              value: http://kuickconfigserver
            - name: TINGYUN_APP_NAME
              value: deal-core2-server
            - name: TINGYUN_ENABLED
              value: "true"
            - name: TINGYUN_LICENSE_KEY
              value: 660743e058f2b474d65cfd6114417bd7
            - name: aliyun_logs_dealcore2server-stdout
              value: stdout
            - name: aliyun_logs_dealcore2server_ttl
              value: "15"
            - name: JAVA_OPTS
              value: -Duser.timezone=GMT+8  -javaagent:/skywalking/agent/skywalking-agent.jar
            - name: SW_AGENT_NAME
              value: deal-core2-server
            - name: SW_AGENT_COLLECTOR_BACKEND_SERVICES
              value: skywalking-skywalking-oap.kuick-prod.svc.cluster.local:11800
          image: registry.cn-hangzhou.aliyuncs.com/zjy-namespace/deal-core2-server:2.0
          imagePullPolicy: Always
          resources:
            limits:
              cpu: "1"
              memory: 2Gi
            requests:
              cpu: "1"
              memory: 2Gi
          name: deal-core2-server
          securityContext:
            capabilities: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /usr/skywalking/agent
              name: sw-agent
            - name: tomcat-log
              mountPath: /tmp/logs/deal-core2-server
      initContainers:
        - image: spring2go/skywalking-agent-sidecar:6.6.0
          name: sw-agent-sidecar
          imagePullPolicy: IfNotPresent
          command: ["sh"]
          args:
            [
              "-c",
              "mkdir -p /skywalking/agent && cp -r /usr/skywalking/agent/* /skywalking/agent",
            ]
          volumeMounts:
            - mountPath: /skywalking/agent
              name: sw-agent

      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      volumes:
        - emptyDir: {}
          name: sw-agent
        - name: tomcat-log
          emptyDir: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/manage/metrics"
    prometheus.io/port: "8081"
  namespace: kuick-prod
  name: deal-core2-server
spec:
  ports:
    - port: 30006
      protocol: TCP
      targetPort: 8080
  selector:
    app: deal-core2-server
  type: ClusterIP