apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: {{ template "template-server.fullname" . }}-config
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "template-server.fullname" . }}-config
{{- if .Values.configmap }}
data:
  Corefile: |-
          {{ range .Values.servers }}
          {{- range $idx, $zone := .zones }}{{ if $idx }} {{ else }}{{ end }}{{ default "" $zone.scheme }}{{ default "." $zone.zone }}{{ else }}.{{ end -}}
          {{- if .port }}:{{ .port }} {{ end -}}
      {
          {{- range .plugins }}
          {{ .name }}{{ if .parameters }} {{ .parameters }}{{ end }}{{ if .configBlock }} {
          {{ .configBlock | indent 12 }}
          }{{ end }}
          {{- end }}
      }
          {{ end }}
        {{- range .Values.zoneFiles }}
        {{ .filename }}: {{ toYaml .contents | indent 4 }}
        {{- end }}
{{- end }}